# permissions for end users to edit documents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: testoperator
    app.kubernetes.io/managed-by: kustomize
  name: documents-editor-role
rules:
- apiGroups:
  - rag.nutslove
  resources:
  - documents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rag.nutslove
  resources:
  - documents/status
  verbs:
  - get
