---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - rag.nutslove
  resources:
  - documents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rag.nutslove
  resources:
  - documents/finalizers
  verbs:
  - update
- apiGroups:
  - rag.nutslove
  resources:
  - documents/status
  verbs:
  - get
  - patch
  - update
